
export interface Hematologia{
  nombre:string;
  documento:number;
  telefono:number;
  codigo:number;
  atencion:string;
  entrega:string;
  eritrocitaria:string;
  leucocitaria:string;
  plaquetaria:string;
  neutrofilos:number;
  linfocitos:number;
  eosinofilos:number;
  monocitos:number;
  basofilos:number;
  gota:string;
  hemoglobina:number;
  hematocrito:number;
  plaquetas:number;
  reticulocitos:number;
  minutosangria:number;
  segundosangria:number;
  minutocoagulacion:number;
  segundocoagulacion:number;
  sicklemia:string;
  eritrosedimentacion:number;
  key$?:string;
}
